routes/web.php
<?php

use App\Client;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', ['middleware' => 'auth',function(){//先にミドルウェアを通す事でログイン判断ができる
  $clients = Client::orderBy('id', 'desc')->paginate(10);

	return view('clients.index', compact('clients'));
}]);


Route::resource("orders","OrderController");//受注
Route::resource("clients","ClientController");//顧客
Route::resource("constructions","ConstructionController");//工事マスタ
Route::resource("constdetails","ConstdetailController");//工事詳細
Route::resource("letters","LetterController");//郵便物
Route::resource("constracts","ConstractController");//契約
Route::resource("types","TypeController");//種別
Route::resource("sends","SendController");//送付
Route::resource("sample/csv",'CsvController');//CSV出力

Auth::Routes();

app/Constdetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Constdetail extends Model
{
    public function clients(){
      return $this->belongTo('App\client');
    }
    public function constracts(){
      return $this->belongTo('App\constract');
    }
    public function costructions(){
      return $this->belongTo('App\construction');
    }
    public function orders(){
      return $this->belongTo('App\order');
    }
}

app/Http/Controllers/ConstdetailController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Constdetail;
use Illuminate\Http\Request;

class ConstdetailController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$constdetails = Constdetail::orderBy('id', 'desc')->paginate(10);

		return view('constdetails.index', compact('constdetails'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('constdetails.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$constdetail = new Constdetail();

		$constdetail->constract_id = $request->input("constract_id");
        $constdetail->client_id = $request->input("client_id");
        $constdetail->construction_id = $request->input("construction_id");
        $constdetail->order_id = $request->input("order_id");

		$constdetail->save();

		return redirect()->route('constdetails.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$constdetail = Constdetail::findOrFail($id);

		return view('constdetails.show', compact('constdetail'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$constdetail = Constdetail::findOrFail($id);

		return view('constdetails.edit', compact('constdetail'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$constdetail = Constdetail::findOrFail($id);

		$constdetail->constract_id = $request->input("constract_id");
        $constdetail->client_id = $request->input("client_id");
        $constdetail->construction_id = $request->input("construction_id");
        $constdetail->order_id = $request->input("order_id");

		$constdetail->save();

		return redirect()->route('constdetails.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$constdetail = Constdetail::findOrFail($id);
		$constdetail->delete();

		return redirect()->route('constdetails.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/constdetails/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Constdetails / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('constdetails.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('constract_id')) has-error @endif">
                       <label for="constract_id-field">Constract_id</label>
                    <input type="text" id="constract_id-field" name="constract_id" class="form-control" value="{{ old("constract_id") }}"/>
                       @if($errors->has("constract_id"))
                        <span class="help-block">{{ $errors->first("constract_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('client_id')) has-error @endif">
                       <label for="client_id-field">Client_id</label>
                    <input type="text" id="client_id-field" name="client_id" class="form-control" value="{{ old("client_id") }}"/>
                       @if($errors->has("client_id"))
                        <span class="help-block">{{ $errors->first("client_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('construction_id')) has-error @endif">
                       <label for="construction_id-field">Construction_id</label>
                    <input type="text" id="construction_id-field" name="construction_id" class="form-control" value="{{ old("construction_id") }}"/>
                       @if($errors->has("construction_id"))
                        <span class="help-block">{{ $errors->first("construction_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('order_id')) has-error @endif">
                       <label for="order_id-field">Order_id</label>
                    <input type="text" id="order_id-field" name="order_id" class="form-control" value="{{ old("order_id") }}"/>
                       @if($errors->has("order_id"))
                        <span class="help-block">{{ $errors->first("order_id") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('constdetails.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/constdetails/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Constdetails / Edit #{{$constdetail->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('constdetails.update', $constdetail->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('constract_id')) has-error @endif">
                       <label for="constract_id-field">Constract_id</label>
                    <input type="text" id="constract_id-field" name="constract_id" class="form-control" value="{{ is_null(old("constract_id")) ? $constdetail->constract_id : old("constract_id") }}"/>
                       @if($errors->has("constract_id"))
                        <span class="help-block">{{ $errors->first("constract_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('client_id')) has-error @endif">
                       <label for="client_id-field">Client_id</label>
                    <input type="text" id="client_id-field" name="client_id" class="form-control" value="{{ is_null(old("client_id")) ? $constdetail->client_id : old("client_id") }}"/>
                       @if($errors->has("client_id"))
                        <span class="help-block">{{ $errors->first("client_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('construction_id')) has-error @endif">
                       <label for="construction_id-field">Construction_id</label>
                    <input type="text" id="construction_id-field" name="construction_id" class="form-control" value="{{ is_null(old("construction_id")) ? $constdetail->construction_id : old("construction_id") }}"/>
                       @if($errors->has("construction_id"))
                        <span class="help-block">{{ $errors->first("construction_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('order_id')) has-error @endif">
                       <label for="order_id-field">Order_id</label>
                    <input type="text" id="order_id-field" name="order_id" class="form-control" value="{{ is_null(old("order_id")) ? $constdetail->order_id : old("order_id") }}"/>
                       @if($errors->has("order_id"))
                        <span class="help-block">{{ $errors->first("order_id") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('constdetails.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/constdetails/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Constdetails
            <a class="btn btn-success pull-right" href="{{ route('constdetails.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($constdetails->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>CONSTRACT_ID</th>
                        <th>CLIENT_ID</th>
                        <th>CONSTRUCTION_ID</th>
                        <th>ORDER_ID</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($constdetails as $constdetail)
                            <tr>
                                <td>{{$constdetail->id}}</td>
                                <td>{{$constdetail->constract_id}}</td>
                    <td>{{$constdetail->client_id}}</td>
                    <td>{{$constdetail->construction_id}}</td>
                    <td>{{$constdetail->order_id}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('constdetails.show', $constdetail->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('constdetails.edit', $constdetail->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('constdetails.destroy', $constdetail->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $constdetails->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/constdetails/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Constdetails / Show #{{$constdetail->id}}</h1>
        <form action="{{ route('constdetails.destroy', $constdetail->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('constdetails.edit', $constdetail->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="constract_id">CONSTRACT_ID</label>
                     <p class="form-control-static">{{$constdetail->constract_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="client_id">CLIENT_ID</label>
                     <p class="form-control-static">{{$constdetail->client_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="construction_id">CONSTRUCTION_ID</label>
                     <p class="form-control-static">{{$constdetail->construction_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="order_id">ORDER_ID</label>
                     <p class="form-control-static">{{$constdetail->order_id}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('constdetails.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection